"""
Generate all fixture ZIP files for tests/test_full.py.
Run once: python tests/conftest.py
Or auto-generated by pytest via session fixture.

Structure: each fixture is a flat ZIP with images/ and texts/ subfolders.
"""
import io
import os
import sys
import zipfile
from pathlib import Path

import pytest

FIXTURES = Path(__file__).parent / "fixtures"

# Minimal valid 1x1 white PNG bytes
PNG_1x1 = (
    b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01'
    b'\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f\x00'
    b'\x00\x01\x01\x00\x05\x18\xd8N\x00\x00\x00\x00IEND\xaeB`\x82'
)


def _make_docx(sections):
    """sections: list of (number, name, content) → docx bytes with table."""
    from docx import Document  # type: ignore
    doc = Document()
    table = doc.add_table(rows=len(sections), cols=1)
    for i, (num, name, content) in enumerate(sections):
        cell = table.cell(i, 0)
        cell.text = f"{num}. {name}\n\n{content}"
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _make_txt(sections):
    lines = []
    for num, name, content in sections:
        lines.append(f"{num}. {name}")
        lines.append("")
        lines.append(content)
        lines.append("")
        lines.append("")
    return "\n".join(lines).encode("utf-8")


def _make_flat_zip(images: dict, texts: dict) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for lang, (fname, data) in images.items():
            zf.writestr(f"images/{fname}", data)
        for lang, (fname, data) in texts.items():
            zf.writestr(f"texts/{fname}", data)
    return buf.getvalue()


# ── Section text constants ────────────────────────────────────────────────────

PIC_TEXT_EN    = "Win up to 500 tokens in our Valentine spin game! Play now!"
BANNER_TEXT_EN = "Valentine Day -15% OFF Tokens Only Feb 13-15"
NEWS_TEXT_EN   = "Read the latest news about our platform updates and new features."
LOGO_TEXT_EN   = "LOGO"

PIC_TEXT_RU    = "Выиграйте до 500 токенов в нашей игре. Играйте сейчас!"
BANNER_TEXT_RU = "День Валентина -15% скидка на токены только 13-15 февраля"
NEWS_TEXT_RU   = "Читайте последние новости о нашей платформе и новых функциях."

PIC_TEXT_HE    = "זכה עד 500 אסימונים במשחק הסיבוב שלנו! שחק עכשיו!"
BANNER_TEXT_HE = "יום האהבה -15% הנחה על אסימונים רק 13-15 בפברואר"
NEWS_TEXT_HE   = "קרא את החדשות האחרונות על הפלטפורמה שלנו ועל תכונות חדשות."

LONG_TEXT = " ".join(["word"] * 70)


# ── Individual scenario builders ─────────────────────────────────────────────

def _scenario1():
    """4 sections: 3.NEWS, 5.PIC, 7.BANNER, 10.LOGO"""
    secs = [(3, "NEWS", NEWS_TEXT_EN), (5, "PIC", PIC_TEXT_EN),
            (7, "BANNER", BANNER_TEXT_EN), (10, "LOGO", LOGO_TEXT_EN)]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.docx", _make_docx(secs))})


def _scenario2():
    secs = [(1, "PIC", PIC_TEXT_EN), (2, "NEWS", NEWS_TEXT_EN), (7, "BANNER", BANNER_TEXT_EN)]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.docx", _make_docx(secs))})


def _scenario3():
    secs = [(1, "PIC", PIC_TEXT_EN), (2, "NEWS", NEWS_TEXT_EN), (7, "BANNER", BANNER_TEXT_EN)]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.docx", _make_docx(secs))})


def _scenario4():
    """Multi-lang: en + ru + he, each with PIC + BANNER + NEWS."""
    return _make_flat_zip(
        images={"en": ("en.png", PNG_1x1), "ru": ("ru.png", PNG_1x1), "he": ("he.png", PNG_1x1)},
        texts={
            "en": ("en.docx", _make_docx([(5,"PIC",PIC_TEXT_EN),(7,"BANNER",BANNER_TEXT_EN),(3,"NEWS",NEWS_TEXT_EN)])),
            "ru": ("ru.docx", _make_docx([(5,"PIC",PIC_TEXT_RU),(7,"BANNER",BANNER_TEXT_RU),(3,"NEWS",NEWS_TEXT_RU)])),
            "he": ("he.docx", _make_docx([(5,"PIC",PIC_TEXT_HE),(7,"BANNER",BANNER_TEXT_HE),(3,"NEWS",NEWS_TEXT_HE)])),
        },
    )


def _scenario5():
    """All sections have placeholders → should trigger MANUAL."""
    secs = [
        (5, "PIC", "%displayname% won %amount% tokens! Click [here] to claim!"),
        (7, "BANNER", "Dear %username%, your discount is [code] valid until <date>!"),
    ]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.docx", _make_docx(secs))})


def _scenario6():
    """en has text, ru image exists but NO text file."""
    en_secs = [(5, "PIC", PIC_TEXT_EN), (7, "BANNER", BANNER_TEXT_EN)]
    return _make_flat_zip(
        images={"en": ("en.png", PNG_1x1), "ru": ("ru.png", PNG_1x1)},
        texts={"en": ("en.docx", _make_docx(en_secs))},
    )


def _scenario7():
    """Various filename patterns: banner_en_700x420.png, Campaign (en).docx"""
    return _make_flat_zip(
        images={"en": ("banner_en_700x420.png", PNG_1x1), "ru": ("banner_ru_700x420.png", PNG_1x1)},
        texts={
            "en": ("Campaign (en).docx", _make_docx([(5,"PIC",PIC_TEXT_EN)])),
            "ru": ("Campaign (ru).docx", _make_docx([(5,"PIC",PIC_TEXT_RU)])),
        },
    )


def _scenario8():
    """LOGO section (10) with short text; others have long text → penalty."""
    secs = [(1,"NEWS",LONG_TEXT), (5,"PIC",LONG_TEXT), (10,"LOGO",LOGO_TEXT_EN), (7,"BANNER",LONG_TEXT)]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.docx", _make_docx(secs))})


def _scenario9():
    """TXT format instead of DOCX."""
    secs = [(5, "PIC", PIC_TEXT_EN), (7, "BANNER", BANNER_TEXT_EN)]
    return _make_flat_zip({"en": ("en.png", PNG_1x1)}, {"en": ("en.txt", _make_txt(secs))})


_SCENARIOS = {
    "scenario1_section_hint.zip": _scenario1,
    "scenario2_name_hint.zip":    _scenario2,
    "scenario3_both_hints.zip":   _scenario3,
    "scenario4_multilang.zip":    _scenario4,
    "scenario5_all_placeholders.zip": _scenario5,
    "scenario6_missing_text.zip": _scenario6,
    "scenario7_filename_patterns.zip": _scenario7,
    "scenario8_long_text.zip":    _scenario8,
    "scenario9_txt_format.zip":   _scenario9,
}


def generate_fixtures(fixtures_dir: Path = FIXTURES) -> None:
    """Generate all fixture ZIPs into fixtures_dir. Safe to call multiple times."""
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    for name, fn in _SCENARIOS.items():
        dest = fixtures_dir / name
        if not dest.exists():
            dest.write_bytes(fn())


# ── pytest session fixture: auto-generate before any test ────────────────────

@pytest.fixture(scope="session", autouse=True)
def ensure_fixtures():
    generate_fixtures()


# ── Standalone: run as script to regenerate all ──────────────────────────────
if __name__ == "__main__":
    generate_fixtures()
    for name in _SCENARIOS:
        p = FIXTURES / name
        print(f"  {name}: {p.stat().st_size} bytes")
    print(f"\nAll fixtures in {FIXTURES}")
